services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:22.16.0
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    ports:
      - 80:3002
    command: npm run dev
    depends_on:
      - storage