services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    build: .
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    ports:
      - 80:3002
    depends_on:
      - storage